"""STEP 3 -- f_K-slice band content for EVERY published k-resolved run.

sim25 (mel_2fk, mr_fK), sim37 (saw, suhl), sim38 (plus, minus) and all 24
sim40 checkpoints, in one table with one convention.

Conventions: saw_analysis.py / CONVENTIONS.md, via rc_common.band_six.
    python step3_band_content.py
"""
from __future__ import annotations
import os
import csv
import hashlib
import numpy as np
import saw_analysis as sa
import rc_common as rc

EPS = [1e-5, 3e-5, 5e-5, 7e-5, 1e-4, 3e-4, 1e-3, 3e-3]
LABELS = ["full_2fK", "full_fK", "mr_fK"]


def runs():
    """(dataset, run, m_xt, dx, dt, f_K, k_saw, pump_note) for every run."""
    d25 = np.load(os.path.join(rc.DATA, "sim25_kspectrum.npz"))
    d37 = np.load(os.path.join(rc.DATA, "sim37_suhl_control.npz"))
    d38 = np.load(os.path.join(rc.DATA, "sim38_nonreciprocal.npz"))
    fK25 = float(d25["f_K"])
    yield ("sim25", "mel_2fk", d25["mel_2fk_my_xt"], float(d25["CX"]),
           float(d25["DT_REC"]), fK25, float(d25["mel_2fk_kSAW"]),
           "MEL pump at 2 f_K, +x")
    yield ("sim25", "mr_fK", d25["mr_fk_my_xt"], float(d25["CX"]),
           float(d25["DT_REC"]), fK25, float(d25["mr_fk_kSAW"]),
           "MR direct drive at f_K, +x")
    fK37 = float(d37["f_K"])
    yield ("sim37", "saw", d37["saw_my_xt"], float(d37["CX"]),
           float(d37["DT_REC"]), fK37, float(d37["saw_kSAW"]),
           "SAW MEL pump at 2 f_K, +x")
    yield ("sim37", "suhl", d37["suhl_my_xt"], float(d37["CX"]),
           float(d37["DT_REC"]), fK37, float(d37["saw_kSAW"]),
           "uniform Suhl pump, k_pump = 0; k_SAW column is the MEL geometry "
           "carried over for comparison only")
    fK38 = float(d38["f_K"])
    yield ("sim38", "plus", d38["plus_my_xt"], float(d38["CX"]),
           float(d38["DT_REC"]), fK38, float(d38["k_SAW"]),
           "SAW MEL pump at 2 f_K, +x")
    yield ("sim38", "minus", d38["minus_my_xt"], float(d38["CX"]),
           float(d38["DT_REC"]), fK38, float(d38["k_SAW"]),
           "SAW MEL pump at 2 f_K, -x (saw_wavevector = -k)")
    for lab in LABELS:
        for e in EPS:
            r = rc.load_sim40(lab, e)
            yield ("sim40", "%s eps=%.0e" % (lab, e), r["m"], r["dx"],
                   r["dt"], r["f_K"], rc.k_saw_of(r["f_saw"]),
                   "f_SAW = %.0f GHz" % (r["f_saw"] / 1e9))


def main():
    out_rows = []
    for ds, run, m, dx, dt, fK, ksaw, note in runs():
        sl = rc.fk_slice(m, dx, dt, fK)
        b = rc.band_six(sl["k"], sl["M"], ksaw / 2, ksaw, quantity="power")
        P = sa.power(sl["M"])
        jmax = int(np.argmax(P))
        sha = hashlib.sha256(np.ascontiguousarray(m).tobytes()).hexdigest()[:16]
        fr = b["fractions"]
        out_rows.append(dict(
            dataset=ds, run=run, n_x=m.shape[1], n_t_used=sl["n_t_used"],
            f_K_GHz=fK / 1e9, f_bin_GHz=sl["f_used"] / 1e9,
            f_mismatch_bins=sl["f_mismatch_bins"], dk_um=sl["dk"] / 1e6,
            k_SAW_um=ksaw / 1e6, k_SAW_over_dk=b["k_saw_over_dk"],
            k_half_over_dk=b["k_pair_over_dk"],
            bins_pair="%+d,%+d" % tuple(
                np.array(b["bins_pair"]) - int(np.argmin(np.abs(sl["k"])))),
            bins_saw="%+d,%+d" % tuple(
                np.array(b["bins_saw"]) - int(np.argmin(np.abs(sl["k"])))),
            f_k0=fr["k0"], f_pair_plus=fr["plus"], f_pair_minus=fr["minus"],
            f_saw_plus=fr["saw_plus"], f_saw_minus=fr["saw_minus"],
            f_rest=fr["rest"], sum_check=b["sum_check"],
            stolen_total=int(sum(b["stolen"].values())),
            argmax_k_um=sl["k"][jmax] / 1e6, argmax_frac=float(P[jmax] / P.sum()),
            total_power=b["total"], array_sha256_16=sha, note=note))
        print("  %-6s %-22s  k0=%.4f pair+=%.4f pair-=%.4f saw+=%.4f "
              "saw-=%.4f rest=%.4f  argmax=%+8.4f"
              % (ds, run, fr["k0"], fr["plus"], fr["minus"], fr["saw_plus"],
                 fr["saw_minus"], fr["rest"], sl["k"][jmax] / 1e6))

    cols = list(out_rows[0].keys())
    with open(os.path.join(rc.HERE, "band_content.csv"), "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for r in out_rows:
            w.writerow(r)

    # ------------------------------------------------------------- markdown
    L = []
    P_ = L.append
    P_("# f_K-slice band content -- every published k-resolved run")
    P_("")
    P_("Generated by `python step3_band_content.py`. Machine-readable twin:")
    P_("`band_content.csv`. Module `saw_analysis.py`; conventions in")
    P_("`CONVENTIONS.md`. Reads `data/` only.")
    P_("")
    P_("## Convention (one, stated once, used for every row)")
    P_("")
    P_("| item | choice |")
    P_("|---|---|")
    P_("| transform | `M(k,f) = sum m w exp(-i k x + i 2 pi f t)`; a wave `exp(i(k x - w t))` with k, f > 0 lands at (+k, +f) |")
    P_("| time range | the SECOND HALF of each record |")
    P_("| windows | Hann in t, rectangular in x (the box is periodic), block mean removed |")
    P_("| quantity | POWER, `\|M\|^2` |")
    P_("| f slice | the single bin nearest that run's own f_K; no interpolation, no f averaging |")
    P_("| k_SAW | that run's own pump wavevector, `2 pi f_SAW / v_SAW`, taken POSITIVE for every run so that a direction reversal shows up as weight moving between the `+` and `-` columns instead of being absorbed into the definition |")
    P_("| pair bins | exactly the TWO bins straddling `+k_SAW/2`; likewise for `-k_SAW/2` |")
    P_("| SAW bins | exactly the TWO bins straddling `+k_SAW`; likewise for `-k_SAW` |")
    P_("| k = 0 | the single k = 0 bin |")
    P_("| disjointness | `saw_analysis.band_content` assigns in the order k0, pair+, pair-, saw+, saw-, rest and removes already-claimed bins from every later mask. The six fractions sum to 1 and `stolen` counts any collision. |")
    P_("")
    P_("`k_SAW/2` is off the k grid in every run here, which is why 'the two")
    P_("straddling bins' is the honest mask and a single 'peak bin' is not.")
    P_("")
    P_("## Table")
    P_("")
    P_("Fractions of that run's f_K-slice power. Columns sum to 1 by")
    P_("construction (`sum` column).")
    P_("")
    P_("| dataset | run | N_x | k_SAW (um^-1) | k_SAW/dk | pair bins | k=0 | pair + | pair - | SAW + | SAW - | rest | sum | argmax k (um^-1) | argmax frac |")
    P_("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for r in out_rows:
        P_("| %s | %s | %d | %.4f | %.4f | %s | %.4f | %.4f | %.4f | %.4f | "
           "%.4f | %.4f | %.6f | %+.4f | %.4f |"
           % (r["dataset"], r["run"], r["n_x"], r["k_SAW_um"],
              r["k_SAW_over_dk"], r["bins_pair"], r["f_k0"], r["f_pair_plus"],
              r["f_pair_minus"], r["f_saw_plus"], r["f_saw_minus"],
              r["f_rest"], r["sum_check"], r["argmax_k_um"], r["argmax_frac"]))
    P_("")
    P_("## Grid and frequency bookkeeping")
    P_("")
    P_("| dataset | run | N_x | dk (um^-1) | n_t used | f_K (GHz) | f bin used (GHz) | offset (bins) | k_SAW/dk | k_SAW/2 /dk | collisions |")
    P_("|---|---|---|---|---|---|---|---|---|---|---|")
    for r in out_rows:
        P_("| %s | %s | %d | %.7f | %d | %.6f | %.6f | %+.3f | %.4f | %.4f | %d |"
           % (r["dataset"], r["run"], r["n_x"], r["dk_um"], r["n_t_used"],
              r["f_K_GHz"], r["f_bin_GHz"], r["f_mismatch_bins"],
              r["k_SAW_over_dk"], r["k_half_over_dk"], r["stolen_total"]))
    P_("")
    P_("## Array identity (measured, not inferred)")
    P_("")
    P_("`sha256` of the raw `my_xt` bytes, first 16 hex digits, over the array")
    P_("exactly as stored. Equal digests mean the SAME array, whatever produced")
    P_("it; unequal digests mean different arrays. This says nothing about")
    P_("which source file generated either -- provenance for the existing runs")
    P_("is NOT DETERMINABLE FROM FILES -- but identity is directly measurable")
    P_("and it is measured here.")
    P_("")
    P_("| dataset / run | sha256[:16] |")
    P_("|---|---|")
    seen = {}
    for r in out_rows:
        if r["dataset"] == "sim40":
            continue
        P_("| %s / %s | `%s` |" % (r["dataset"], r["run"], r["array_sha256_16"]))
        seen.setdefault(r["array_sha256_16"], []).append(
            "%s/%s" % (r["dataset"], r["run"]))
    dup = {h: v for h, v in seen.items() if len(v) > 1}
    P_("")
    if dup:
        for h, v in dup.items():
            P_("**Bit-identical arrays:** %s all carry `%s`. They are one run,"
               % (", ".join("`%s`" % x for x in v), h))
            P_("not three. That is why their rows in the table above are")
            P_("identical to every printed digit.")
        P_("")
    else:
        P_("No two of these arrays are bit-identical.")
        P_("")
    P_("## Per-run notes")
    P_("")
    for r in out_rows:
        if r["dataset"] != "sim40":
            P_("- **%s / %s** -- %s" % (r["dataset"], r["run"], r["note"]))
    P_("- **sim40** -- `full_2fK` is pumped at f_SAW = 6 GHz, so its k_SAW is")
    P_("  10.7712 um^-1 and its pair band is at 5.3856 um^-1. `full_fK` and")
    P_("  `mr_fK` are pumped at f_SAW = 3 GHz, so their k_SAW is 5.3856 um^-1")
    P_("  and their `SAW +` column, not their `pair +` column, is the forced")
    P_("  response. Comparing `pair +` across the three sim40 channels compares")
    P_("  different wavevectors; comparing `full_2fK`'s `pair +` with the other")
    P_("  two channels' `SAW +` compares the same one (5.3856 um^-1).")
    P_("")
    P_("## What this table can and cannot decide")
    P_("")
    P_("It CAN refute a band assignment: if the advertised weight is not in the")
    P_("`pair +` column it is not there, and the `argmax` column says where it")
    P_("actually is. That is a falsifiable statement and the table makes it")
    P_("run by run.")
    P_("")
    P_("It CANNOT count modes. Control (d) of `test_saw_analysis.py` puts a")
    P_("SINGLE off-grid sinusoid at 5.5 um^-1 on this grid and the two")
    P_("straddling bins take 0.8087 of the positive-k power, with a `pair +`")
    P_("fraction of 0.857. A large `pair +` is therefore consistent with one")
    P_("leaked wave and with two phase-locked components alike.")
    open(os.path.join(rc.HERE, "band_content.md"), "w").write("\n".join(L))
    print("\nwrote band_content.md and band_content.csv (%d runs)" % len(out_rows))


if __name__ == "__main__":
    main()
