"""STEP 4 -- SAW direction reversal done as a COORDINATE TRANSFORM.

sim38 holds both propagation directions.  `src/make_fig3_killer_evidence.py`
does not transform the k axis: it SWAPS the two datasets, plotting
`minus_my_xt` under the label '+k_SAW pump'.  Here the axis is handled by the
module's fixed transform instead (equivalent to k_plot = -k_fft applied to an
fft2 pipeline, verified to 3.8e-16 by `test_fft2_equivalence`), each run keeps
its own label, and the centroid is quantified with and without the k = 0 and
|k| = k_SAW regions.

Conventions: saw_analysis.py / CONVENTIONS.md.
    python step4_reversal.py
"""
from __future__ import annotations
import os
import numpy as np
import saw_analysis as sa
import rc_common as rc

d38 = np.load(os.path.join(rc.DATA, "sim38_nonreciprocal.npz"))
CX = float(d38["CX"]); DT = float(d38["DT_REC"])
F_K = float(d38["f_K"]); K_SAW = float(d38["k_SAW"])

RUNS = [("plus_my_xt", "+k_SAW pump (saw_wavevector = +k)"),
        ("minus_my_xt", "-k_SAW pump (saw_wavevector = -k)")]


def centroid(k, w):
    s = w.sum()
    return (float((k * w).sum() / s) if s > 0 else np.nan), float(s)


def main():
    L = []
    P = L.append
    P("# SAW direction reversal -- coordinate transform, not dataset swap")
    P("")
    P("Generated by `python step4_reversal.py`. Module `saw_analysis.py`;")
    P("conventions in `CONVENTIONS.md`. Reads `data/sim38_nonreciprocal.npz`")
    P("only.")
    P("")
    P("## The fix")
    P("")
    P("`src/make_fig3_killer_evidence.py:61-67` states that the FFT convention")
    P("flips the apparent peak sign and therefore feeds `minus_my_xt` to the")
    P("panel labelled '+k_SAW pump' and `plus_my_xt` to the panel labelled")
    P("'-k_SAW pump'. The premise is right and the remedy is not. An fft2")
    P("pipeline sliced at positive f does show the physical +k peak at -k, and")
    P("the repair for that is a sign flip of the PLOTTED AXIS -- a relabelling")
    P("of one figure's x coordinate. Exchanging the two datasets produces the")
    P("same picture only when the two runs happen to be mirrors, and it")
    P("silently files each physical run under the other's label.")
    P("`make_fig5_v3.py` gets this right with `k_disp = -k_fft`. This module")
    P("removes the need for either by fixing the transform itself; the")
    P("equivalence `|M(k,+f)| = |F_fft2(-k,+f)|` is verified to 3.8e-16.")
    P("")
    P("Below, each run keeps its own label and NOTHING is swapped.")
    P("")
    P("## Setup")
    P("")
    P("| item | value |")
    P("|---|---|")
    P("| window | second half of the record, Hann in t, rect in x, detrended |")
    P("| f slice | the single bin nearest f_K |")
    P("| k_SAW | %.6f um^-1 (stored in the file) |" % (K_SAW / 1e6))
    P("| restriction | `\\|k\\| <= 1.5 k_SAW`, the same restriction `make_fig3` uses |")
    P("| exclusions | E1 = the k = 0 bin; E2 = E1 plus the two bins straddling each of +/-k_SAW; E3 = E1 plus a +/-2 dk window about each of +/-k_SAW |")
    P("")
    res = {}
    for key, lbl in RUNS:
        sl = rc.fk_slice(d38[key], CX, DT, F_K)
        k = sl["k"]; dk = sl["dk"]
        Pw = sa.power(sl["M"]); Am = sa.amplitude(sl["M"])
        band = np.abs(k) <= 1.5 * K_SAW
        j0 = int(np.argmin(np.abs(k)))
        _, (sl_lo, sl_hi), _ = rc.straddle(k, K_SAW)
        _, (ml_lo, ml_hi), _ = rc.straddle(k, -K_SAW)
        e1 = band.copy(); e1[j0] = False
        e2 = e1.copy()
        for j in (sl_lo, sl_hi, ml_lo, ml_hi):
            e2[j] = False
        e3 = e1 & (np.abs(np.abs(k) - K_SAW) > 2 * dk)
        e3 &= band
        res[key] = dict(k=k, Pw=Pw, Am=Am, masks=dict(all=band, E1=e1, E2=e2,
                                                      E3=e3), lbl=lbl, dk=dk,
                        sl=sl)
    P("## Centroids")
    P("")
    P("`residual` is the fraction of the `|k| <= 1.5 k_SAW` weight that")
    P("survives the exclusion, in the same weighting as the centroid.")
    P("")
    P("| run | weighting | mask | centroid k (um^-1) | centroid / (k_SAW/2) | residual weight |")
    P("|---|---|---|---|---|---|")
    table = {}
    for key, lbl in RUNS:
        r = res[key]
        for qname, w in (("power", r["Pw"]), ("amplitude", r["Am"])):
            base = w[r["masks"]["all"]].sum()
            for mname in ("all", "E1", "E2", "E3"):
                m = r["masks"][mname]
                c, s = centroid(r["k"][m], w[m])
                table[(key, qname, mname)] = (c, s / base)
                P("| %s | %s | %s | %+.4f | %+.4f | %.6f |"
                  % (lbl, qname, mname, c / 1e6, c / (K_SAW / 2), s / base))
    P("")
    P("## Sign statement")
    P("")
    for qname in ("power", "amplitude"):
        for mname in ("all", "E1", "E2", "E3"):
            cp = table[("plus_my_xt", qname, mname)][0]
            cm = table[("minus_my_xt", qname, mname)][0]
            P("- %s / %s: k_bar(+pump) = %+.4f, k_bar(-pump) = %+.4f um^-1; "
              "signs %s; |ratio| = %.4f"
              % (qname, mname, cp / 1e6, cm / 1e6,
                 "OPPOSE" if cp * cm < 0 else "AGREE (no reversal)",
                 abs(cp / cm) if cm != 0 else np.inf))
    P("")
    P("## Reproduction of the published Fig. 3(c) centroid, and the swap")
    P("")
    P("`make_fig3_killer_evidence.py::slice_at_fk` differs from the convention")
    P("of this directory in four ways: it uses the FULL record, a Hann window")
    P("in x, an average over `|f - f_K| <= 200 MHz` rather than one bin, and a")
    P("Gaussian smoothing of sigma = 1.5 bins. Running that exact recipe:")
    P("")
    from scipy.ndimage import gaussian_filter1d

    def pub_slice(m_xt, fwin=2e8, sigma=1.5, wx="hann", trange=None,
                  one_bin=False):
        k, f, M = sa.spectrum(m_xt, CX, DT, window="hann", window_x=wx,
                              trange=trange)
        Pw = sa.power(M)
        if one_bin:
            i, _ = sa.f_slice(M, f, F_K)
            S = Pw[i, :]
        else:
            S = Pw[np.abs(f - F_K) <= fwin, :].mean(axis=0)
        if sigma:
            S = gaussian_filter1d(S, sigma)
        return k, S

    def cbar(k, S):
        b = np.abs(k) <= 1.5 * K_SAW
        return float((k[b] * S[b]).sum() / S[b].sum())

    # `pub_slice` returns the PHYSICAL k axis (= -k_fft).  The published
    # figure plots the raw fft axis, so its printed centroid is the negative.
    kP, SP = pub_slice(d38["plus_my_xt"])
    kM, SM = pub_slice(d38["minus_my_xt"])
    cP, cM = cbar(kP, SP), cbar(kM, SM)
    P("| what it does | run fed | axis plotted | k_bar as printed (um^-1) | / (k_SAW/2) |")
    P("|---|---|---|---|---|")
    P("| published panel '+k_SAW pump' | `minus_my_xt` | raw fft | %+.4f | %+.4f |"
      % (-cM / 1e6, -cM / (K_SAW / 2)))
    P("| published panel '-k_SAW pump' | `plus_my_xt` | raw fft | %+.4f | %+.4f |"
      % (-cP / 1e6, -cP / (K_SAW / 2)))
    P("| coordinate transform, '+k_SAW pump' | `plus_my_xt` | `-k_fft` = physical | %+.4f | %+.4f |"
      % (cP / 1e6, cP / (K_SAW / 2)))
    P("| coordinate transform, '-k_SAW pump' | `minus_my_xt` | `-k_fft` = physical | %+.4f | %+.4f |"
      % (cM / 1e6, cM / (K_SAW / 2)))
    P("")
    P("The published pair (%+.2f, %+.2f) um^-1 is reproduced exactly."
      % (-cM / 1e6, -cP / 1e6))
    P("The coordinate transform returns a pair of the same two magnitudes,")
    P("differing by %.1f%%, with the runs correctly assigned to the labels."
      % (100 * abs(abs(cP / cM) - 1)))
    P("So the published PANEL is not misdrawn; the published METHOD is, and")
    P("only the near-mirror symmetry of this particular pair of runs kept the")
    P("error invisible. On any dataset where the two directions are not near")
    P("mirrors the swap would print one run under the other's label, and the")
    P("figure would assert the opposite of what was simulated.")
    P("")
    P("## Processing sensitivity of the centroid")
    P("")
    P("The centroid is not a robust number on this dataset. Varying only the")
    P("processing, on the SAME `plus_my_xt` run, physical k axis:")
    P("")
    P("| time range | x window | f treatment | smoothing | k_bar (um^-1) | k_bar / (k_SAW/2) |")
    P("|---|---|---|---|---|---|")
    for trange, tn in ((None, "full record"),
                       (rc.second_half(d38["plus_my_xt"].shape[0]), "second half"),
                       ((200, 600), "t = 4-12 ns")):
        for wx in ("rect", "hann"):
            for one_bin, fn in ((True, "single bin"), (False, "+/-200 MHz mean")):
                for sg, sn in ((0, "none"), (1.5, "sigma = 1.5")):
                    k5, S5 = pub_slice(d38["plus_my_xt"], sigma=sg, wx=wx,
                                       trange=trange, one_bin=one_bin)
                    c5 = cbar(k5, S5)
                    P("| %s | %s | %s | %s | %+.4f | %+.4f |"
                      % (tn, wx, fn, sn, c5 / 1e6, c5 / (K_SAW / 2)))
    P("")
    P("The same run gives centroids from about 0.53 to 0.99 of k_SAW/2")
    P("depending only on choices that carry no physics. A quoted")
    P("`k_bar ~ +k_SAW/2` is therefore a statement about the processing as much")
    P("as about the spectrum, and the convention must be printed with it.")
    P("")
    P("## Exclusion-width sweep -- where the sign statement stops holding")
    P("")
    P("The E2/E3 rows above show the centroid sign is NOT carried by the")
    P("residual. Because that depends on how wide the excluded |k| = k_SAW")
    P("region is, the width is swept rather than chosen. `W` is the half-width")
    P("in units of dk about each of +/-k_SAW; the k = 0 bin is always removed;")
    P("the band is always `|k| <= 1.5 k_SAW`.")
    P("")
    P("| W (dk) | k_bar(+pump) power | k_bar(-pump) power | opposed? | residual + | residual - |")
    P("|---|---|---|---|---|---|")
    for W in [0.0, 0.5, 1.0, 2.0, 3.0, 4.0, 6.0, 8.0]:
        vals = {}
        for key, _ in RUNS:
            r = res[key]; k = r["k"]; w = r["Pw"]
            j0 = int(np.argmin(np.abs(k)))
            m = (np.abs(k) <= 1.5 * K_SAW)
            base = w[m].sum()
            m = m & (np.abs(np.abs(k) - K_SAW) > W * r["dk"])
            m[j0] = False
            c, s = centroid(k[m], w[m])
            vals[key] = (c, s / base)
        cp, rp = vals["plus_my_xt"]; cm, rm = vals["minus_my_xt"]
        P("| %.1f | %+.4f | %+.4f | %s | %.6f | %.6f |"
          % (W, cp / 1e6, cm / 1e6, "yes" if cp * cm < 0 else "NO", rp, rm))
    P("")
    P("## Mirror test")
    P("")
    P("If the reversal is exact, `S_+(k) = S_-(-k)` bin by bin. Measured on")
    P("the `|k| <= 1.5 k_SAW` band:")
    P("")
    kp = res["plus_my_xt"]["k"]
    band = res["plus_my_xt"]["masks"]["all"]
    Sp = res["plus_my_xt"]["Pw"]
    Sm = res["minus_my_xt"]["Pw"]
    # k -> -k on an fftshifted axis k[j] = (j - N/2) dk: the partner of j is
    # N - j, i.e. mirror = roll(reverse, 1).  Index 0 is the lone Nyquist bin,
    # which has no positive counterpart and is excluded below.
    Sm_mirror = np.roll(Sm[::-1], 1)
    km = np.roll((-kp)[::-1], 1)
    ok = np.ones_like(kp, dtype=bool); ok[0] = False
    assert np.allclose(km[ok], kp[ok], atol=1e-6), \
        "k axis is not symmetric under k->-k"
    band = band & ok
    a, b_ = Sp[band], Sm_mirror[band]
    rel = float(np.abs(a - b_).sum() / (a.sum() + b_.sum()))
    corr = float(np.corrcoef(a, b_)[0, 1])
    P("| quantity | value |")
    P("|---|---|")
    P("| Pearson r between S_+(k) and S_-(-k) | %.6f |" % corr)
    P("| sum |S_+(k) - S_-(-k)| / (sum S_+ + sum S_-) | %.6f |" % rel)
    P("| Pearson r between S_+(k) and S_-(k), i.e. WITHOUT the mirror | %.6f |"
      % float(np.corrcoef(Sp[band], Sm[band])[0, 1]))
    j0b = int(np.argmin(np.abs(kp)))
    bnk = band.copy(); bnk[j0b] = False
    P("| same three, k = 0 bin removed: mirrored | %.6f |"
      % float(np.corrcoef(Sp[bnk], Sm_mirror[bnk])[0, 1]))
    P("| same three, k = 0 bin removed: un-mirrored | %.6f |"
      % float(np.corrcoef(Sp[bnk], Sm[bnk])[0, 1]))
    P("")
    P("The un-mirrored rows are the control. The k = 0 bin is common to both")
    P("runs and inflates any correlation that includes it, which is why the")
    P("same pair is reported with it removed. The mirrored correlation exceeds")
    P("the un-mirrored one in both cases; had it not, the mirror claim would be")
    P("refuted.")
    P("")
    P("## Where the weight actually is")
    P("")
    P("From `band_content.md`, same convention, same window:")
    P("")
    P("| run | k = 0 | pair + | pair - | SAW + | SAW - | rest |")
    P("|---|---|---|---|---|---|---|")
    for key, lbl in RUNS:
        r = res[key]
        b = rc.band_six(r["k"], r["sl"]["M"], K_SAW / 2, K_SAW,
                        quantity="power")
        f = b["fractions"]
        P("| %s | %.4f | %.4f | %.4f | %.4f | %.4f | %.4f |"
          % (lbl, f["k0"], f["plus"], f["minus"], f["saw_plus"],
             f["saw_minus"], f["rest"]))
    P("")
    P("## What the reversal establishes, and what it does not")
    P("")
    P("**ESTABLISHES (a sign statement, at the level of the whole spectrum).**")
    P("The f_K-slice weight mirrors under reversal: with the common k = 0 bin")
    P("removed, `S_+(k)` correlates with `S_-(-k)` at r = 0.710 and with")
    P("`S_-(+k)` at r = 0.168. That is a fourfold separation on the same bins,")
    P("and it is the falsifiable form of the claim -- had the un-mirrored")
    P("correlation matched or exceeded the mirrored one, the reversal would be")
    P("refuted. The kernel makes it expected rather than surprising:")
    P("`chiralsawfield.cu:69` computes `phase = sawK*coord - sawOmega*t +")
    P("sawPhi` and `sim38_nonreciprocal.py` really does set")
    P("`saw_wavevector = -k` for the reversed run, so the sign enters the")
    P("physics and comes back out of the measurement.")
    P("")
    P("**DOES NOT ESTABLISH a reversing RESIDUAL.** The centroid sign flip is")
    P("carried by the `|k| = k_SAW` lobes and does not survive their removal.")
    P("The sweep is explicit: the two power-weighted centroids oppose at")
    P("exclusion half-widths W = 0 and 0.5 dk, and AGREE IN SIGN for")
    P("W = 1, 2, 3, 4 and 6 dk, over residual weights of 0.17-0.50. The one")
    P("further reversal at W = 8 dk is on 17-25% of the weight and is not")
    P("claimed as anything. So the honest statement is that the reversal is a")
    P("property of the k = 0 and |k| = k_SAW lobes; after removing them the")
    P("residual is INDISTINGUISHABLE FROM NO REVERSAL with current data.")
    P("")
    P("**DOES NOT ESTABLISH a pair band at k_SAW/2.** The centroid is an")
    P("average, and the table above shows what it is averaging: the `pair +`")
    P("and `pair -` columns together hold about 1% of the slice, while `k = 0`")
    P("and the two `SAW` columns hold the bulk. A centroid near k_SAW/2 is")
    P("what a split between a k = 0 lobe and a k = k_SAW lobe produces")
    P("arithmetically; it is not evidence of weight AT k_SAW/2. The `E2` and")
    P("`E3` rows are the direct test -- they remove both lobes and report the")
    P("residual weight fraction, so the reader can see how little is left and")
    P("where it sits.")
    P("")
    P("**DOES NOT ESTABLISH two components.** Nothing here counts modes; see")
    P("`DISCRIMINATION_TABLE.md`.")
    open(os.path.join(rc.HERE, "direction_reversal.md"), "w").write("\n".join(L))
    print("\n".join(L))


if __name__ == "__main__":
    main()
