"""STEP 2 -- corrected pair coherence C(k_1) for the MEL, MR and uniform-Suhl
runs, with the amplitude-preserving conditional null and an explicit power gate.

Conventions: saw_analysis.py / CONVENTIONS.md.
    python step2_coherence.py            (N_SURR = 200000 by default)
"""
from __future__ import annotations
import os
import time
import numpy as np
import saw_analysis as sa
import rc_common as rc

N_SURR = int(os.environ.get("N_SURR", 200000))
M_SEG = 6
SEED = 20260917

d25 = np.load(os.path.join(rc.DATA, "sim25_kspectrum.npz"))
d37 = np.load(os.path.join(rc.DATA, "sim37_suhl_control.npz"))
CX = float(d37["CX"])
DT = float(d37["DT_REC"])
F_K = float(d37["f_K"])                       # 2.977172 GHz
K_SAW = float(d37["saw_kSAW"])                # 10.689215 um^-1
OMEGA_P = 2 * np.pi * (2 * F_K)

# Windows: exactly those of the published sim39_normalized_correlator.py.
#   MEL  -- sim37 saw run, growth window t in [4,12] ns   (indices 200:600)
#   MR   -- sim25 mr_fk run, second half                   (500:1001)
#   Suhl -- sim37 suhl run, second half                    (500:1001)
CHANNELS = [
    ("MEL_SAW_2fK", d37["saw_my_xt"], (int(4e-9 / DT), int(12e-9 / DT)),
     K_SAW, "sim37_suhl_control.npz:saw_my_xt"),
    ("MR_direct_fK", d25["mr_fk_my_xt"], None, K_SAW,
     "sim25_kspectrum.npz:mr_fk_my_xt"),
    ("uniform_Suhl", d37["suhl_my_xt"], None, 0.0,
     "sim37_suhl_control.npz:suhl_my_xt"),
]


def run_channel(m_xt, trange):
    m = np.asarray(m_xt, dtype=np.float64)
    if trange is None:
        trange = rc.second_half(m.shape[0])
    i0, i1 = trange
    seg_len = (i1 - i0) // M_SEG
    k, f, Ms, t_s = sa.segment_spectra(
        m, CX, DT, seg_len=seg_len, n_seg=M_SEG, stride=seg_len, t0=i0,
        window=rc.WINDOW_T, window_x=rc.WINDOW_X, detrend=True)
    i_f, _ = sa.f_slice(Ms[0], f, F_K)
    S = Ms[:, i_f, :]                         # (n_seg, n_k) complex f_K slice
    return k, f, S, t_s, i_f, seg_len


# `targets()` and the published-row selection now live in rc_common.py so that
# test_saw_analysis.py can exercise them directly (audit 2026-09-18, section 5).
targets = rc.targets

L = []
P = L.append
P("# Corrected pair coherence C(k_1) -- sim25 / sim37")
P("")
P("Generated by `python step2_coherence.py` (N_SURR = %d, seed %d)."
  % (N_SURR, SEED))
P("Module `saw_analysis.py`; conventions in `CONVENTIONS.md`. Reads")
P("`data/` only.")
P("")
P("## What changed, and what fixed it")
P("")
P("`src/sim39_normalized_correlator.py` builds its spectra with `np.fft.fft2`,")
P("whose segment factor is `exp(+i 2 pi f t_s)`, so the pair product ALREADY")
P("carries `exp(+i omega_p t_s)`. Pre-multiplying each factor by")
P("`sqrt(pump_phase)` multiplies the product by `exp(+i omega_p t_s)` a second")
P("time and DOUBLES the rotation instead of removing it. In this module's")
P("convention the correct correction is `phase_sign = +1`, and the published")
P("error is reproduced by `phase_sign = -1`.")
P("")
P("The sign is fixed by a control, not by an argument: control (a) of")
P("`test_saw_analysis.py` builds two exactly phase-locked waves and returns")
P("C = 1.000000000000 for the correct sign and 0.2357022604 for the wrong one,")
P("the latter matching the analytic residual `|<exp(-2 i omega_p t_s)>|` to")
P("1e-9.")
P("")
P("## Correction of 2026-09-18 -- which null the percentile came from")
P("")
P("An independent audit (section 5 of `SAW_handover_verification_2026-09-18.md`)")
P("found that the row used for the `1/sqrt(M)` percentile was picked by a fixed")
P("position in the target list, `npub = min(2, n-1)`. The list merges duplicate")
P("bins, and on this 2048-cell axis the bin nearest `+k_SAW/2` IS the upper")
P("straddling bin, so the published point merges into row 1 and position 2 is")
P("the near-`k_SAW` row. The percentile was therefore quoted from the wrong")
P("null: 50.7 (MEL) and 57.5 (MR) belong to the near-`k_SAW` null, not to the")
P("half-`k_SAW` null of the published point. The row is now located by")
P("wavenumber and pair partner (`rc_common.select_target_row`), which raises")
P("instead of falling back; the regression test is")
P("`test_saw_analysis.py::test_null_row_is_requested_target`.")
P("")
P("C = 0.5877 and the conditional exceedance 0.778 at the published point are")
P("unchanged by this correction -- they were never in question. Only the")
P("percentile of `1/sqrt(M)` moves, and it moves a long way.")
P("")
P("## Method")
P("")
P("| item | value |")
P("|---|---|")
P("| segments | M = %d Welch segments, contiguous, Hann in t, rect in x, detrended |" % M_SEG)
P("| f slice | the bin nearest f_K = %.6f GHz, no interpolation |" % (F_K / 1e9))
P("| omega_p | 2 pi x 2 f_K = %.6e rad/s, the exact pump, never a segment bin centre |" % OMEGA_P)
P("| null | %d surrogates; per-segment, per-k MAGNITUDES kept exactly, phases randomised |" % N_SURR)
P("| p | one-sided: fraction of surrogates with C_null >= C_obs |")
P("")
P("The null is CONDITIONAL on the measured amplitude structure. It is not")
P("`1/sqrt(M)`, which is the null of a phase-only resultant and not the null")
P("of the amplitude-weighted statistic that is actually computed.")
P("")
P("## Reproduction of the published numbers")
P("")
P("Before correcting anything, the `phase_sign = -1` column below is checked")
P("against the shipped `data/sim39_normalized_correlator.npz`, at the bin the")
P("published figure plots as `+k_SAW/2` (the fft-axis bin at -5.5223 um^-1).")
P("")
d39 = np.load(os.path.join(rc.DATA, "sim39_normalized_correlator.npz"))
k39 = d39["k_um"]
j39 = int(np.argmin(np.abs(k39 + float(d39["k_half_um"]))))
P("| shipped array | shipped value at that bin |")
P("|---|---|")
for nm in ("C_mel_saw", "C_mr", "C_suhl"):
    P("| `%s` | %.4f |" % (nm, float(d39[nm][j39])))
P("")
P("If the `C published sign` entries below match these, the diagnosis is")
P("established rather than asserted: the published pipeline and")
P("`phase_sign = -1` are the same calculation.")
P("")

rows = []
for name, m_xt, trange, K_pump, src in CHANNELS:
    k, f, S, t_s, i_f, seg_len = run_channel(m_xt, trange)
    df_seg = float(f[1] - f[0])
    f_used = float(f[i_f])
    degen = (2 * F_K) * (seg_len * DT)
    P("## %s" % name)
    P("")
    P("- source: `data/%s`" % src)
    P("- window: %s" % ("t in [4, 12] ns (indices %d:%d), the published"
                        " growth window" % trange if trange else
                        "second half of the record"))
    P("- segment length %d samples = %.4f ns; K_pump = %.6f um^-1"
      % (seg_len, seg_len * DT * 1e9, K_pump / 1e6))
    P("- f slice: nearest bin is %.6f GHz, %+.3f segment bins from f_K "
      "(df_seg = %.2f MHz). %d-sample segments cannot localise f_K better "
      "than that." % (f_used / 1e9, (f_used - F_K) / df_seg, df_seg / 1e6,
                      seg_len))
    P("- stride degeneracy: f_pump x stride x dt = %.4f. Were this an integer, "
      "`exp(i omega_p t_s)` would equal 1 in every segment and the sign would "
      "be untestable. It is not." % degen)
    P("")
    res_p = sa.pair_correlator(S, t_s, k, K_pump, OMEGA_P, phase_sign=+1)
    res_m = sa.pair_correlator(S, t_s, k, K_pump, OMEGA_P, phase_sign=-1)
    j2 = res_p["j2"]
    tg = targets(k, K_pump, k_ref=K_SAW)
    idx = np.array([j for j, _ in tg])
    t0 = time.time()
    null = sa.pair_correlator_null(S, t_s, k, K_pump, OMEGA_P,
                                   n_real=N_SURR, k_indices=idx, seed=SEED,
                                   phase_sign=+1)
    el = time.time() - t0
    Pw = (np.abs(S) ** 2).sum(axis=0)          # segment-summed power
    tot = float(Pw.sum())
    P("| k_1 (um^-1) | what it is | partner k_2 (um^-1) | snap err (um^-1) | "
      "C corrected | C published sign | null q50 | null q95 | null q99 | p | "
      "power frac k_1 | power frac k_2 |")
    P("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for n, (j, lbl) in enumerate(tg):
        Cn = null["C_null"][:, n]
        p = float((Cn >= res_p["C"][j]).mean())
        snap = (K_pump - k[j]) - k[j2[j]]
        P("| %.4f | %s | %.4f | %.4f | **%.4f** | %.4f | %.4f | %.4f | %.4f | "
          "%.4f | %.3e | %.3e |"
          % (k[j] / 1e6, lbl, k[j2[j]] / 1e6, snap / 1e6, res_p["C"][j],
             res_m["C"][j], null["quantiles"]["q50"][n],
             null["quantiles"]["q95"][n], null["quantiles"]["q99"][n], p,
             Pw[j] / tot, Pw[j2[j]] / tot))
        rows.append([name, float(k[j] / 1e6), lbl, float(res_p["C"][j]),
                     float(res_m["C"][j]),
                     float(null["quantiles"]["q95"][n]), p,
                     float(Pw[j] / tot), float(Pw[j2[j]] / tot)])
    P("")
    # The published point is the half-k_SAW target; the row is located by that
    # wavenumber and its pair partner, never by a position in the list
    # (audit 2026-09-18, section 5).
    npub = rc.select_target_row(tg, k, j2, K_SAW / 2, K_pump)
    jpub = idx[npub]
    P("`1/sqrt(M)` = %.4f for M = %d. In THIS channel's own null at the "
      "PUBLISHED POINT, k_1 = %.4f um^-1 (%s), partner k_2 = %.4f um^-1, it "
      "sits at the %.4f-th percentile, so it is not a 95%% threshold and must "
      "not be drawn as one."
      % (1 / np.sqrt(M_SEG), M_SEG, k[jpub] / 1e6, tg[npub][1],
         k[j2[jpub]] / 1e6,
         100 * float((null["C_null"][:, npub] <= 1 / np.sqrt(M_SEG)).mean())))
    P("")
    P("- null RMS at that row: %.9f (mean of C_null^2, square-rooted)"
      % float(np.sqrt((null["C_null"][:, npub] ** 2).mean())))
    P("- observed C at that row: %.9f ; conditional exceedance "
      "P(C_null >= C_obs) = %.6f"
      % (res_p["C"][jpub],
         float((null["C_null"][:, npub] >= res_p["C"][jpub]).mean())))
    P("- both are CONDITIONAL on the measured per-segment, per-k magnitudes, "
      "which the surrogates keep exactly while randomising phases. The "
      "exceedance is not an unconditional p-value over the physical ensemble.")
    P("")
    P("(null: %d surrogates x %d bins in %.1f s; max partner snap error over "
      "the whole axis %.4f um^-1)"
      % (N_SURR, idx.size, el, res_p["snap_error_max"] / 1e6))
    P("")

P("## Summary")
P("")
P("| channel | bin | C published (shipped) | C corrected | null q95 | p | power frac |")
P("|---|---|---|---|---|---|---|")
for r in rows:
    if "PUBLISHED POINT" in r[2] or r[2] == "k = 0":
        P("| %s | %.4f | %.4f | %.4f | %.4f | %.4f | %.3e |"
          % (r[0], r[1], r[4], r[3], r[5], r[6], r[7]))
P("")
P("Three statements follow, and only these three.")
P("")
P("1. The published ordering `0.81 > 0.56 > 0.41` is an artefact of the sign.")
P("   With the sign corrected the MEL and MR values swap places at the")
P("   published point. The corrected triplet must NOT be substituted for the")
P("   published one: at that point neither MEL nor MR is distinguishable from")
P("   its own amplitude-preserving surrogate (p >> 0.05).")
P("2. In the MEL run the bins that ARE phase-rigid beyond their surrogate are")
P("   `k = 0` and `k = +k_SAW` -- the non-degenerate (0, k_SAW) partition --")
P("   not the degenerate pair at `+k_SAW/2`. That is a measurement, and it")
P("   points the same way as the band-content table of `band_content.md`.")
P("3. The uniform-Suhl control is where the power gate earns its place:")
P("   C = 0.9997 on bins holding 5.09e-08 of that slice's power. The number is")
P("   arithmetically correct and physically empty.")
P("")
P("## Power gate")
P("")
P("`power frac` above is that bin's share of the SAME f_K slice, summed over")
P("the M segments: `sum_s |M_s(k)|^2 / sum_s sum_k |M_s(k)|^2`. A normalised")
P("coherence divides amplitude out by construction, so it returns a number of")
P("order one on bins holding an arbitrarily small share of the power. A C")
P("quoted without its power share is unreadable, which is why both columns are")
P("here and why neither may be reported without the other.")
P("")
P("## Falsifiability of this diagnostic")
P("")
P("The null is the falsifier and it is free to fail to reject. A C above the")
P("99th percentile of its own amplitude-preserving surrogate would establish")
P("segment-to-segment phase rigidity beyond what the measured amplitudes alone")
P("produce; a C at or below the null median refutes any such claim for that")
P("bin. The table states which happened, per bin, per channel, with the")
P("p-value. Control (b) of `test_saw_analysis.py` shows the null behaves:")
P("197/200 independent-phase realisations land inside its [0.5%, 99%] interval.")
P("")
P("## Register -- what a high C does NOT establish")
P("")
P("Control (e) of `test_saw_analysis.py` returns C = 1.000000 for a SINGLE")
P("off-grid wave leaking into two bins, exactly as it does for two genuinely")
P("phase-locked components. The pair correlator is therefore evidence against")
P("independent thermal populations and nothing more. It cannot count modes and")
P("it cannot establish the finite-momentum pair.")

txt = "\n".join(L)
open(os.path.join(rc.HERE, "coherence_corrected.md"), "w").write(txt)
np.save(os.path.join(rc.OUT, "step2_coherence_rows.npy"),
        np.array(rows, dtype=object), allow_pickle=True)
print(txt)
